/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.newProductFrame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.text.DecimalFormat;
import java.time.Instant;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import mercadinhoprojectSrc.bdManager;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
/**
 *
 * @author Aluno
 */

public class newProductFrame extends javax.swing.JFrame {
    /**
     * Creates new form mainFrame
     */
    
    int validateProductImgChange = 0;
    
    Path originFileForFinalInsert = Path.of("");
    Path destinyFileForFinalInsert = Path.of("");
    
    public static String formatToCamelCase(String input) {
        String[] words = input.split(" ");
        StringBuilder result = new StringBuilder();

        for (int i = 0; i < words.length; i++) {
            String word = words[i].toLowerCase();
            if (i > 0) {
                char firstWord = Character.toUpperCase(word.charAt(0));
                word = firstWord + word.substring(1);
            }
            result.append(word);
        }
        return result.toString();
    }
    
    public newProductFrame() {
        initComponents();
        UtilDateModel model = new UtilDateModel();
        JDatePanelImpl datePanel = new JDatePanelImpl(model);
        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);
        jPanel1.add(datePicker);
        txtProductImgPath.setVisible(false);
        txtProductImgPath.setVisible(false);
        txtOriginFile.setVisible(false);
        txtDestinyFile.setVisible(false);
        
        txtName.setText("Cinto de couro");
        txtDescription.setText("Cinto revestido de couro da mais alta qualidade.");
        txtEanCode.setText("78998465776");
        txtNcm.setText("48769184");
        txtStockQtd.setText("20");
        txtRegisterDate.setText("01/06/2023");
        txtStatus.setText("A");
        txtMinStockQtd.setText("10");
        txtMaxStockQtd.setText("50");
        txtBuyAmount.setText("5");
        txtSaleAmount.setText("15");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackToMainFrame = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        txtTitle2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLoadProductImg = new javax.swing.JButton();
        imgProductImage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelImgTitle = new javax.swing.JLabel();
        labelImgTitle1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        labelImgTitle2 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        labelImgTitle3 = new javax.swing.JLabel();
        txtStockQtd = new javax.swing.JTextField();
        labelImgTitle4 = new javax.swing.JLabel();
        txtRegisterDate = new javax.swing.JTextField();
        labelImgTitle5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelImgTitle6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        labelImgTitle7 = new javax.swing.JLabel();
        txtMinStockQtd = new javax.swing.JTextField();
        labelImgTitle8 = new javax.swing.JLabel();
        txtMaxStockQtd = new javax.swing.JTextField();
        labelImgTitle9 = new javax.swing.JLabel();
        txtBuyAmount = new javax.swing.JTextField();
        labelImgTitle10 = new javax.swing.JLabel();
        txtSaleAmount = new javax.swing.JTextField();
        labelImgTitle11 = new javax.swing.JLabel();
        txtProfitAmount = new javax.swing.JTextField();
        labelImgTitle12 = new javax.swing.JLabel();
        txtNcm = new javax.swing.JTextField();
        labelImgTitle13 = new javax.swing.JLabel();
        txtEanCode = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        labelImgTitle14 = new javax.swing.JLabel();
        txtProductImgPath = new javax.swing.JTextField();
        txtTitle4 = new javax.swing.JLabel();
        txtOriginFile = new javax.swing.JTextField();
        txtDestinyFile = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(212, 211, 212));

        btnBackToMainFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-left.png"))); // NOI18N
        btnBackToMainFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackToMainFrameMouseClicked(evt);
            }
        });

        txtTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        txtTitle.setText("Novo produto");

        txtTitle2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtTitle2.setText("Voltar");
        txtTitle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTitle2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));

        btnLoadProductImg.setText("Carregar imagem");
        btnLoadProductImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadProductImgActionPerformed(evt);
            }
        });

        imgProductImage.setBackground(new java.awt.Color(228, 227, 227));
        imgProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nullImage.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(0, 2));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 2));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel4.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        labelImgTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle.setText("Imagem do produto");

        labelImgTitle1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle1.setText("Código do produto");

        txtCode.setEditable(false);
        txtCode.setMaximumSize(new java.awt.Dimension(105, 30));
        txtCode.setMinimumSize(new java.awt.Dimension(105, 30));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        labelImgTitle2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle2.setText("Status");

        txtStatus.setMaximumSize(new java.awt.Dimension(50, 30));
        txtStatus.setMinimumSize(new java.awt.Dimension(50, 30));
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        labelImgTitle3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle3.setText("Quantidade em estoque");

        txtStockQtd.setMaximumSize(new java.awt.Dimension(55, 30));
        txtStockQtd.setMinimumSize(new java.awt.Dimension(55, 30));
        txtStockQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockQtdActionPerformed(evt);
            }
        });

        labelImgTitle4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle4.setText("Data de cadastro");

        txtRegisterDate.setEditable(false);
        txtRegisterDate.setMaximumSize(new java.awt.Dimension(105, 30));
        txtRegisterDate.setMinimumSize(new java.awt.Dimension(105, 30));
        txtRegisterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterDateActionPerformed(evt);
            }
        });

        labelImgTitle5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle5.setText("Nome do produto");

        txtName.setMaximumSize(new java.awt.Dimension(260, 30));
        txtName.setMinimumSize(new java.awt.Dimension(260, 30));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        labelImgTitle6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle6.setText("Descrição");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setMaximumSize(new java.awt.Dimension(260, 70));
        txtDescription.setMinimumSize(new java.awt.Dimension(260, 70));
        jScrollPane1.setViewportView(txtDescription);

        labelImgTitle7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle7.setText("Estoque mínimo");

        txtMinStockQtd.setMaximumSize(new java.awt.Dimension(55, 30));
        txtMinStockQtd.setMinimumSize(new java.awt.Dimension(55, 30));
        txtMinStockQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinStockQtdActionPerformed(evt);
            }
        });

        labelImgTitle8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle8.setText("Estoque máximo");

        txtMaxStockQtd.setMaximumSize(new java.awt.Dimension(55, 30));
        txtMaxStockQtd.setMinimumSize(new java.awt.Dimension(55, 30));
        txtMaxStockQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxStockQtdActionPerformed(evt);
            }
        });

        labelImgTitle9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle9.setText("Preço de compra");

        txtBuyAmount.setMaximumSize(new java.awt.Dimension(100, 30));
        txtBuyAmount.setMinimumSize(new java.awt.Dimension(100, 30));
        txtBuyAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuyAmountFocusLost(evt);
            }
        });
        txtBuyAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyAmountActionPerformed(evt);
            }
        });

        labelImgTitle10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle10.setText("Preço de venda");

        txtSaleAmount.setMaximumSize(new java.awt.Dimension(100, 30));
        txtSaleAmount.setMinimumSize(new java.awt.Dimension(100, 30));
        txtSaleAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSaleAmountFocusLost(evt);
            }
        });
        txtSaleAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaleAmountActionPerformed(evt);
            }
        });

        labelImgTitle11.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle11.setText("Fator lucro");

        txtProfitAmount.setEditable(false);
        txtProfitAmount.setMaximumSize(new java.awt.Dimension(55, 30));
        txtProfitAmount.setMinimumSize(new java.awt.Dimension(55, 30));
        txtProfitAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfitAmountActionPerformed(evt);
            }
        });

        labelImgTitle12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle12.setText("NCM");

        txtNcm.setMaximumSize(new java.awt.Dimension(100, 30));
        txtNcm.setMinimumSize(new java.awt.Dimension(100, 30));
        txtNcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNcmActionPerformed(evt);
            }
        });

        labelImgTitle13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle13.setText("Código de barras GTIN/EAN");

        txtEanCode.setMaximumSize(new java.awt.Dimension(55, 30));
        txtEanCode.setMinimumSize(new java.awt.Dimension(55, 30));
        txtEanCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEanCodeActionPerformed(evt);
            }
        });

        btnRegister.setText("Cadastrar produto");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        labelImgTitle14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        labelImgTitle14.setText("%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelImgTitle6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImgTitle13)
                                    .addComponent(txtEanCode, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnRegister)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(imgProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImgTitle)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnLoadProductImg))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelImgTitle5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(72, 72, 72)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelImgTitle12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelImgTitle3)
                                            .addComponent(labelImgTitle1)
                                            .addComponent(labelImgTitle4)
                                            .addComponent(txtStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtRegisterDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelImgTitle2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelImgTitle7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMinStockQtd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelImgTitle8)
                                            .addComponent(txtMaxStockQtd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImgTitle9)
                            .addComponent(labelImgTitle10)
                            .addComponent(labelImgTitle11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtProfitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelImgTitle14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBuyAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelImgTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLoadProductImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(labelImgTitle5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(labelImgTitle9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(labelImgTitle4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(labelImgTitle10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(labelImgTitle3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(labelImgTitle11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtProfitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(labelImgTitle14)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(labelImgTitle2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelImgTitle7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMinStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(labelImgTitle8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaxStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelImgTitle1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(labelImgTitle12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelImgTitle6)
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelImgTitle13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEanCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        txtProductImgPath.setEditable(false);
        txtProductImgPath.setEnabled(false);

        txtTitle4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTitle4.setText("Cadastramento de produto");

        txtOriginFile.setEditable(false);
        txtOriginFile.setEnabled(false);

        txtDestinyFile.setEditable(false);
        txtDestinyFile.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBackToMainFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDestinyFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOriginFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProductImgPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTitle4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(txtTitle)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBackToMainFrame)
                            .addComponent(txtTitle2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductImgPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOriginFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestinyFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtTitle4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(txtTitle)
                    .addContainerGap(458, Short.MAX_VALUE)))
        );

        jMenu1.setText("Produtos");

        jMenuItem1.setText("Cadastrar produto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Gerenciar produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMainFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToMainFrameMouseClicked
        this.dispose();
        mainFrame mainFrameInstance = new mainFrame();
        mainFrameInstance.setLocationRelativeTo(null);
        mainFrameInstance.setVisible(true);
    }//GEN-LAST:event_btnBackToMainFrameMouseClicked

    private void txtTitle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTitle2MouseClicked
        btnBackToMainFrameMouseClicked(evt);
    }//GEN-LAST:event_txtTitle2MouseClicked

    private void btnLoadProductImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadProductImgActionPerformed
        JFileChooser fc = new JFileChooser();
        FileFilter ff = new FileNameExtensionFilter("images","jpeg");
        fc.addChoosableFileFilter(ff);
        int open = fc.showOpenDialog(this);
        if (open == javax.swing.JFileChooser.APPROVE_OPTION){
            java.io.File path = fc.getSelectedFile();
            String file_name = path.toString();
            BufferedImage bi;
            try{
                bi = ImageIO.read(path);
                Image resizedImg = bi.getScaledInstance(100, 110, Image.SCALE_SMOOTH);
                ImageIcon iconImg = new ImageIcon(resizedImg);
                imgProductImage.setIcon(iconImg);
                
                String fileUploadedDestiny = "";
                Instant instant = Instant.now();
                    long timestamp = instant.toEpochMilli();
                    txtCode.setText("" + timestamp);
                    fileUploadedDestiny = "../productsImg/" + timestamp + "/";
                
                File fileUploadedDestinyFolder = new File(fileUploadedDestiny);
                if (!fileUploadedDestinyFolder.exists()) {
                    fileUploadedDestinyFolder.mkdirs();
                }
                
                Path originFile = path.toPath();
                String originalFileName = originFile.getFileName().toString();
                
                String fileExtension = originalFileName.substring(originalFileName.lastIndexOf('.'));
                String renamedFileName =  formatToCamelCase(txtName.getText()) + fileExtension;
                
                Path destinyFile = fileUploadedDestinyFolder.toPath().resolve(renamedFileName);
                txtProductImgPath.setText(destinyFile.toString().replace("\\", "__"));

                btnLoadProductImg.setText("Trocar imagem");
                validateProductImgChange = 1;
                originFileForFinalInsert = originFile;
                destinyFileForFinalInsert = destinyFile;
            }
            catch(IOException e){
            }
        }
    }//GEN-LAST:event_btnLoadProductImgActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtStockQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockQtdActionPerformed

    private void txtRegisterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterDateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtMinStockQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinStockQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinStockQtdActionPerformed

    private void txtMaxStockQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxStockQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxStockQtdActionPerformed

    private void txtBuyAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuyAmountActionPerformed

    private void txtSaleAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaleAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaleAmountActionPerformed

    private void txtProfitAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfitAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfitAmountActionPerformed

    private void txtNcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNcmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNcmActionPerformed

    private void txtEanCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEanCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEanCodeActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if(txtName.getText().length() > 0 && txtDescription.getText().length() > 0 && txtEanCode.getText().length() > 0 
                && txtNcm.getText().length() > 0 && txtStockQtd.getText().length() > 0 && txtRegisterDate.getText().length() > 0 
                && txtCode.getText().length() > 0 && txtStatus.getText().length() > 0 && txtMinStockQtd.getText().length() > 0 
                && txtMaxStockQtd.getText().length() > 0 && txtBuyAmount.getText().length() > 0 && txtSaleAmount.getText().length() > 0
                && txtProductImgPath.getText().length() > 0 && txtProfitAmount.getText().length() > 0 && txtCode.getText().length() > 0)
        {
            try {
                Files.copy(originFileForFinalInsert, destinyFileForFinalInsert, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                System.out.println("Erro!");
            }
            BigInteger eanCodeForInsert = new BigInteger(txtEanCode.getText());
            bdManager bdManagerInstance = new bdManager();
            bdManagerInstance.dynamicAddProduct(txtCode.getText(), txtStatus.getText(), txtName.getText(), txtDescription.getText(), Integer.parseInt(txtStockQtd.getText()), Integer.parseInt(txtMinStockQtd.getText()), Integer.parseInt(txtMaxStockQtd.getText()), Float.parseFloat(txtBuyAmount.getText()), Float.parseFloat(txtSaleAmount.getText()), eanCodeForInsert, Integer.parseInt(txtNcm.getText()), Float.parseFloat(txtProfitAmount.getText().replace(",", ".")), txtProductImgPath.getText());
            JOptionPane.showMessageDialog(null, "O produto " + txtName.getText() + " foi cadastrado com sucesso!");
            this.dispose();
            mainFrame mainFrameInstance = new mainFrame();
            mainFrameInstance.setLocationRelativeTo(null);
            mainFrameInstance.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Registro não concluído! Certifique-se de que preencheu TODOS os campos da tela.");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtBuyAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuyAmountFocusLost
        if(txtBuyAmount.getText().length() > 0 && txtSaleAmount.getText().length() > 0){
            DecimalFormat df = new DecimalFormat("0.00");
            float profitAmount = ((((Float.parseFloat(txtSaleAmount.getText()) - Float.parseFloat(txtBuyAmount.getText()))/Float.parseFloat(txtBuyAmount.getText()))*100));
            String profitAmountFormatted = df.format(profitAmount);
            txtProfitAmount.setText(profitAmountFormatted);
        }
    }//GEN-LAST:event_txtBuyAmountFocusLost

    private void txtSaleAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaleAmountFocusLost
        txtBuyAmountFocusLost(evt);
    }//GEN-LAST:event_txtSaleAmountFocusLost

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        productsManagementFrame productsManagementFrameInstance;
        try {
            productsManagementFrameInstance = new productsManagementFrame();
            productsManagementFrameInstance.setLocationRelativeTo(null);
            productsManagementFrameInstance.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackToMainFrame;
    private javax.swing.JButton btnLoadProductImg;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel imgProductImage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImgTitle;
    private javax.swing.JLabel labelImgTitle1;
    private javax.swing.JLabel labelImgTitle10;
    private javax.swing.JLabel labelImgTitle11;
    private javax.swing.JLabel labelImgTitle12;
    private javax.swing.JLabel labelImgTitle13;
    private javax.swing.JLabel labelImgTitle14;
    private javax.swing.JLabel labelImgTitle2;
    private javax.swing.JLabel labelImgTitle3;
    private javax.swing.JLabel labelImgTitle4;
    private javax.swing.JLabel labelImgTitle5;
    private javax.swing.JLabel labelImgTitle6;
    private javax.swing.JLabel labelImgTitle7;
    private javax.swing.JLabel labelImgTitle8;
    private javax.swing.JLabel labelImgTitle9;
    private javax.swing.JTextField txtBuyAmount;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtDestinyFile;
    private javax.swing.JTextField txtEanCode;
    private javax.swing.JTextField txtMaxStockQtd;
    private javax.swing.JTextField txtMinStockQtd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNcm;
    private javax.swing.JTextField txtOriginFile;
    private javax.swing.JTextField txtProductImgPath;
    private javax.swing.JTextField txtProfitAmount;
    private javax.swing.JTextField txtRegisterDate;
    private javax.swing.JTextField txtSaleAmount;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtStockQtd;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTitle2;
    private javax.swing.JLabel txtTitle4;
    // End of variables declaration//GEN-END:variables
}
