/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.productsManagementFrame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mercadinhoprojectSrc.bdManager;
/**
 *
 * @author Aluno
 */
public class productsManagementFrame extends javax.swing.JFrame {
    bdManager bdManagerInstance = new bdManager();
    ArrayList<Vector> products = bdManagerInstance.getAllProducts();
    int activeProduct = 0;
    
    /**
     * Creates new form mainFrame
     */
    public productsManagementFrame() throws IOException {
        initComponents();
        populateActiveProduct("initial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackToMain = new javax.swing.JLabel();
        txtProductTitle = new javax.swing.JLabel();
        txtBackToMainTitle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        imgProductImage = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelImgTitle = new javax.swing.JLabel();
        labelImgTitle1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        labelImgTitle2 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        labelImgTitle4 = new javax.swing.JLabel();
        txtRegisterDate = new javax.swing.JTextField();
        labelImgTitle9 = new javax.swing.JLabel();
        txtBuyAmount = new javax.swing.JTextField();
        labelImgTitle10 = new javax.swing.JLabel();
        txtSaleAmount = new javax.swing.JTextField();
        labelImgTitle7 = new javax.swing.JLabel();
        txtMinStockQtd = new javax.swing.JTextField();
        labelImgTitle8 = new javax.swing.JLabel();
        txtMaxStockQtd = new javax.swing.JTextField();
        labelImgTitle3 = new javax.swing.JLabel();
        txtStockQtd = new javax.swing.JTextField();
        labelImgTitle5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelImgTitle6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        labelImgTitle13 = new javax.swing.JLabel();
        txtEanCode = new javax.swing.JTextField();
        labelImgTitle11 = new javax.swing.JLabel();
        txtProfitAmount = new javax.swing.JTextField();
        labelImgTitle14 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        labelImgTitle12 = new javax.swing.JLabel();
        txtNcm = new javax.swing.JTextField();
        txtProductId = new javax.swing.JTextField();
        labelImgTitle15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTitle4 = new javax.swing.JLabel();
        btnNextProductForRight = new javax.swing.JLabel();
        btnNextProductForLeft = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtTitle5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        txtNowProduct = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(212, 211, 212));

        btnBackToMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-left.png"))); // NOI18N
        btnBackToMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackToMainMouseClicked(evt);
            }
        });

        txtProductTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        txtProductTitle.setText("Produto X");

        txtBackToMainTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtBackToMainTitle.setText("Voltar");
        txtBackToMainTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBackToMainTitleMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(246, 246, 246));

        imgProductImage.setBackground(new java.awt.Color(228, 227, 227));
        imgProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nullImage.png"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setMaximumSize(new java.awt.Dimension(0, 2));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 2));
        jPanel6.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        labelImgTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle.setText("Imagem do produto (Clique para alterar)");

        labelImgTitle1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle1.setText("Código do produto");

        txtCode.setEditable(false);
        txtCode.setMaximumSize(new java.awt.Dimension(105, 30));
        txtCode.setMinimumSize(new java.awt.Dimension(105, 30));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        labelImgTitle2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle2.setText("Status");

        txtStatus.setMaximumSize(new java.awt.Dimension(50, 30));
        txtStatus.setMinimumSize(new java.awt.Dimension(50, 30));
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        labelImgTitle4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle4.setText("Data de cadastro");

        txtRegisterDate.setEditable(false);
        txtRegisterDate.setMaximumSize(new java.awt.Dimension(105, 30));
        txtRegisterDate.setMinimumSize(new java.awt.Dimension(105, 30));
        txtRegisterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterDateActionPerformed(evt);
            }
        });

        labelImgTitle9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle9.setText("Preço de compra");

        txtBuyAmount.setMaximumSize(new java.awt.Dimension(100, 30));
        txtBuyAmount.setMinimumSize(new java.awt.Dimension(100, 30));
        txtBuyAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyAmountActionPerformed(evt);
            }
        });

        labelImgTitle10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle10.setText("Preço de venda");

        txtSaleAmount.setMaximumSize(new java.awt.Dimension(100, 30));
        txtSaleAmount.setMinimumSize(new java.awt.Dimension(100, 30));
        txtSaleAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaleAmountActionPerformed(evt);
            }
        });

        labelImgTitle7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle7.setText("Estoque mínimo");

        txtMinStockQtd.setMaximumSize(new java.awt.Dimension(55, 30));
        txtMinStockQtd.setMinimumSize(new java.awt.Dimension(55, 30));
        txtMinStockQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinStockQtdActionPerformed(evt);
            }
        });

        labelImgTitle8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle8.setText("Estoque máximo");

        txtMaxStockQtd.setMaximumSize(new java.awt.Dimension(55, 30));
        txtMaxStockQtd.setMinimumSize(new java.awt.Dimension(55, 30));
        txtMaxStockQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxStockQtdActionPerformed(evt);
            }
        });

        labelImgTitle3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle3.setText("Quantidade em estoque");

        txtStockQtd.setMaximumSize(new java.awt.Dimension(55, 30));
        txtStockQtd.setMinimumSize(new java.awt.Dimension(55, 30));
        txtStockQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockQtdActionPerformed(evt);
            }
        });

        labelImgTitle5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle5.setText("Nome do produto");

        txtName.setMaximumSize(new java.awt.Dimension(260, 30));
        txtName.setMinimumSize(new java.awt.Dimension(260, 30));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        labelImgTitle6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle6.setText("Descrição");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setMaximumSize(new java.awt.Dimension(260, 70));
        txtDescription.setMinimumSize(new java.awt.Dimension(260, 70));
        jScrollPane1.setViewportView(txtDescription);

        labelImgTitle13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle13.setText("Código de barras GTIN/EAN");

        txtEanCode.setMaximumSize(new java.awt.Dimension(55, 30));
        txtEanCode.setMinimumSize(new java.awt.Dimension(55, 30));
        txtEanCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEanCodeActionPerformed(evt);
            }
        });

        labelImgTitle11.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle11.setText("Fator lucro");

        txtProfitAmount.setMaximumSize(new java.awt.Dimension(55, 30));
        txtProfitAmount.setMinimumSize(new java.awt.Dimension(55, 30));
        txtProfitAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfitAmountActionPerformed(evt);
            }
        });

        labelImgTitle14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        labelImgTitle14.setText("%");

        btnEdit.setText("Editar produto");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        labelImgTitle12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle12.setText("NCM");

        txtNcm.setMaximumSize(new java.awt.Dimension(100, 30));
        txtNcm.setMinimumSize(new java.awt.Dimension(100, 30));
        txtNcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNcmActionPerformed(evt);
            }
        });

        txtProductId.setEditable(false);
        txtProductId.setMaximumSize(new java.awt.Dimension(50, 30));
        txtProductId.setMinimumSize(new java.awt.Dimension(50, 30));
        txtProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIdActionPerformed(evt);
            }
        });

        labelImgTitle15.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        labelImgTitle15.setText("ID do produto");

        jButton1.setBackground(new java.awt.Color(250, 195, 195));
        jButton1.setText("Deletar produto");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelImgTitle10)
                            .addComponent(txtBuyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelImgTitle2)
                            .addComponent(txtRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(txtProfitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelImgTitle14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelImgTitle4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelImgTitle1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelImgTitle9))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txtSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(labelImgTitle15)
                                        .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelImgTitle11))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelImgTitle)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelImgTitle6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelImgTitle13)
                            .addComponent(txtEanCode, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelImgTitle5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelImgTitle8)
                        .addComponent(txtMaxStockQtd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelImgTitle7)
                    .addComponent(txtMinStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImgTitle3)
                    .addComponent(labelImgTitle12)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelImgTitle7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelImgTitle8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelImgTitle5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(labelImgTitle15)
                                        .addGap(9, 9, 9)
                                        .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(labelImgTitle13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEanCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelImgTitle)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelImgTitle6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(labelImgTitle3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStockQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelImgTitle12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labelImgTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelImgTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelImgTitle4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelImgTitle9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtBuyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(labelImgTitle10))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelImgTitle11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtProfitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelImgTitle14))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(24, 24, 24))
        );

        txtTitle4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTitle4.setText("Gerenciador de produtos");

        btnNextProductForRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-right.png"))); // NOI18N
        btnNextProductForRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextProductForRightMouseClicked(evt);
            }
        });

        btnNextProductForLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-left.png"))); // NOI18N
        btnNextProductForLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextProductForLeftMouseClicked(evt);
            }
        });

        txtSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSearchInputMethodTextChanged(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        txtTitle5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtTitle5.setText("Pesquise um produto pelo nome");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        txtNowProduct.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        txtNowProduct.setText("0/0");
        txtNowProduct.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBackToMainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTitle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitle5)
                        .addGap(72, 72, 72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNowProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnNextProductForLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextProductForRight, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(txtProductTitle)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBackToMain)
                                .addComponent(txtBackToMainTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtTitle4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtTitle5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtNowProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNextProductForRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNextProductForLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(txtProductTitle)
                    .addContainerGap(458, Short.MAX_VALUE)))
        );

        jMenu1.setText("Produtos");

        jMenuItem1.setText("Cadastrar produto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Gerenciar produtos");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void searchProductById(int productIdSearched) throws IOException{
        System.out.println(products);
        for(int x = 0; x < products.size(); x++){
            if(Integer.parseInt(products.get(x).get(0).toString()) == productIdSearched){
                activeProduct = products.indexOf(products.get(x));
            }
        }
        populateActiveProduct("searchById");
    }
    
    public void populateActiveProduct(String direction) throws IOException{
        if(products.size() > 0){
            if(direction == "searchById"){
            activeProduct = activeProduct;
            } else {
                if(direction == "initial"){
                activeProduct = 0;
                }

                if(direction == "right"){
                    if(activeProduct == (products.size()-1)){
                        activeProduct = 0;
                    } else{
                        activeProduct = activeProduct+1;
                    }
                } else if(direction == "left"){
                    if(activeProduct == 0){
                        activeProduct = (products.size()-1);
                    } else{
                        activeProduct = activeProduct-1;
                    }
                }
            }
            
            DateTimeFormatter inputFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDateTime dateTimeFormat = LocalDateTime.parse(products.get(activeProduct).get(13).toString(), inputFormat);
            String registerDateFormated = dateTimeFormat.format(outputFormat);

            txtProductId.setText(products.get(activeProduct).get(0).toString());
            txtCode.setText(products.get(activeProduct).get(1).toString());
            txtStatus.setText(products.get(activeProduct).get(2).toString());
            txtName.setText(products.get(activeProduct).get(3).toString());
            txtDescription.setText(products.get(activeProduct).get(4).toString());
            txtStockQtd.setText(products.get(activeProduct).get(5).toString());
            txtMinStockQtd.setText(products.get(activeProduct).get(6).toString());
            txtMaxStockQtd.setText(products.get(activeProduct).get(7).toString());
            txtBuyAmount.setText(products.get(activeProduct).get(8).toString());
            txtSaleAmount.setText(products.get(activeProduct).get(9).toString());
            txtEanCode.setText(products.get(activeProduct).get(10).toString());
            txtNcm.setText(products.get(activeProduct).get(11).toString());
            txtProfitAmount.setText(products.get(activeProduct).get(12).toString());
            txtRegisterDate.setText(registerDateFormated);
            txtProductTitle.setText(txtName.getText());

            String productImage = products.get(activeProduct).get(14).toString().replace("__", "/");
            File file = new File(productImage);
            BufferedImage bi;
            bi = ImageIO.read(file);
            Image resizedImg = bi.getScaledInstance(100, 110, Image.SCALE_SMOOTH);
            ImageIcon iconImg = new ImageIcon(resizedImg);
            imgProductImage.setIcon(iconImg);
            txtNowProduct.setText(Integer.toString((activeProduct+1)) + "/" + Integer.toString(products.size()));
        }
    }
    private void btnBackToMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToMainMouseClicked
        this.dispose();
        mainFrame mainFrameInstance = new mainFrame();
        mainFrameInstance.setLocationRelativeTo(null);
        mainFrameInstance.setVisible(true);
    }//GEN-LAST:event_btnBackToMainMouseClicked

    private void txtBackToMainTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackToMainTitleMouseClicked
        btnBackToMainMouseClicked(evt);
    }//GEN-LAST:event_txtBackToMainTitleMouseClicked

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtRegisterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterDateActionPerformed

    private void txtBuyAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuyAmountActionPerformed

    private void txtSaleAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaleAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaleAmountActionPerformed

    private void txtMinStockQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinStockQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinStockQtdActionPerformed

    private void txtMaxStockQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxStockQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxStockQtdActionPerformed

    private void txtStockQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockQtdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEanCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEanCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEanCodeActionPerformed

    private void txtProfitAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfitAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfitAmountActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        try {
            BigInteger eanCodeForInsert = new BigInteger(txtEanCode.getText());
            bdManagerInstance.dynamicEditProduct(Integer.parseInt(txtProductId.getText()), txtStatus.getText(), txtName.getText(), txtDescription.getText(), Integer.parseInt(txtStockQtd.getText()), Integer.parseInt(txtMinStockQtd.getText()), Integer.parseInt(txtMaxStockQtd.getText()), Float.parseFloat(txtBuyAmount.getText()), Float.parseFloat(txtSaleAmount.getText()), eanCodeForInsert, Integer.parseInt(txtNcm.getText()), Float.parseFloat(txtProfitAmount.getText().replace(",", ".")));
            products = bdManagerInstance.getAllProducts();
            populateActiveProduct("searchById");
            JOptionPane.showMessageDialog(null, "Os dados do produto foram atualizados com sucesso!");
        } catch (IOException ex) {
            Logger.getLogger(productsManagementFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNcmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNcmActionPerformed

    private void btnNextProductForLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextProductForLeftMouseClicked
        try {
            populateActiveProduct("left");
        } catch (IOException ex) {
            Logger.getLogger(productsManagementFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextProductForLeftMouseClicked

    private void btnNextProductForRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextProductForRightMouseClicked
        try {
            populateActiveProduct("right");
        } catch (IOException ex) {
            Logger.getLogger(productsManagementFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextProductForRightMouseClicked

    private void txtProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMouseClicked

    private void txtSearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSearchInputMethodTextChanged
        
    }//GEN-LAST:event_txtSearchInputMethodTextChanged

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        bdManager bdManagerInstance = new bdManager();
        Vector product = bdManagerInstance.getProductByName(txtSearch.getText());
        
        if(product.isEmpty()){
        
        } else {
            for(int i = 0; i < products.size(); i++){
                if(Integer.parseInt(products.get(i).get(0).toString()) == Integer.parseInt(product.get(0).toString())){
                    activeProduct = products.indexOf(products.get(i));
                }
            }
            try {
                populateActiveProduct("searchById");
            } catch (IOException ex) {
                Logger.getLogger(productsManagementFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int awnswer = JOptionPane.showOptionDialog(
                null,
                "Você realmente quer apagar o produto " + txtProductTitle.getText() + " da base de dados do sistema?",
                "Confirmação de exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Sim", "Não"},
                "Sim");

        if (awnswer == JOptionPane.YES_OPTION) {
            bdManagerInstance.deleteProduct(Integer.parseInt(txtProductId.getText()));
            JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!");
            this.dispose();
            mainFrame mainFrameInstance = new mainFrame();
            mainFrameInstance.setLocationRelativeTo(null);
            mainFrameInstance.setVisible(true);
        } else if (awnswer == JOptionPane.NO_OPTION) {
        } else if (awnswer == JOptionPane.CLOSED_OPTION) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        newProductFrame newProductFrameInstance = new newProductFrame();
        newProductFrameInstance.setLocationRelativeTo(null);
        newProductFrameInstance.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new productsManagementFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(productsManagementFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackToMain;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel btnNextProductForLeft;
    private javax.swing.JLabel btnNextProductForRight;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel imgProductImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImgTitle;
    private javax.swing.JLabel labelImgTitle1;
    private javax.swing.JLabel labelImgTitle10;
    private javax.swing.JLabel labelImgTitle11;
    private javax.swing.JLabel labelImgTitle12;
    private javax.swing.JLabel labelImgTitle13;
    private javax.swing.JLabel labelImgTitle14;
    private javax.swing.JLabel labelImgTitle15;
    private javax.swing.JLabel labelImgTitle2;
    private javax.swing.JLabel labelImgTitle3;
    private javax.swing.JLabel labelImgTitle4;
    private javax.swing.JLabel labelImgTitle5;
    private javax.swing.JLabel labelImgTitle6;
    private javax.swing.JLabel labelImgTitle7;
    private javax.swing.JLabel labelImgTitle8;
    private javax.swing.JLabel labelImgTitle9;
    private javax.swing.JLabel txtBackToMainTitle;
    private javax.swing.JTextField txtBuyAmount;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEanCode;
    private javax.swing.JTextField txtMaxStockQtd;
    private javax.swing.JTextField txtMinStockQtd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNcm;
    private javax.swing.JLabel txtNowProduct;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JLabel txtProductTitle;
    private javax.swing.JTextField txtProfitAmount;
    private javax.swing.JTextField txtRegisterDate;
    private javax.swing.JTextField txtSaleAmount;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtStockQtd;
    private javax.swing.JLabel txtTitle4;
    private javax.swing.JLabel txtTitle5;
    // End of variables declaration//GEN-END:variables
}
